# Override configuration for development

services:
  backend:
    environment:
      # Development environment variables
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
      - RELOAD=true
      # Use polling mode for file watching on Windows/Docker (prevents I/O error 5)
      - WATCHFILES_FORCE_POLLING=true
      # Increase watcher timeout to handle Windows Docker startup delays
      - WATCHFILES_RUST_TIMEOUT=10000
    # Override CMD for development without auto-reload (to avoid Windows Docker file watching issues)
    # If you need hot reload, add --reload flag and restart container if you see errors
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --log-level
      - debug
      - --use-colors
      - --access-log
    # Enable code mounting for development (comment out for production)
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
      - uploads_data:/uploads

  # Override database for development with more permissive settings
  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miraiworks
      MYSQL_USER: hrms
      MYSQL_PASSWORD: hrms
      # Allow connections from any host in development
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

volumes:
  backend_logs:
  uploads_data: