site_name: MiraiWorks Documentation
theme:
  name: material
  palette:
    primary: indigo
    accent: purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Architecture: ARCHITECTURE_RECOMMENDATIONS.md
  - Code Review: CODE_REVIEW_GUIDELINES.md
  - Performance: PERFORMANCE_RECOMMENDATIONS.md
  - Security: SECURITY_RECOMMENDATIONS.md
  - Workflow: WORKFLOW_RECOMMENDATIONS.md
  - Recommendations: RECOMMENDATIONS.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourorg/miraiworks
