site_name: MiraiWorks Documentation
theme:
  name: material
  palette:
    primary: indigo
    accent: purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Backend:
    - API Reference: api/index.md
    - Database Schema: backend/database.md
    - Authentication: backend/auth.md
  - Frontend:
    - Components: frontend/components.md
    - State Management: frontend/state.md
    - Routing: frontend/routing.md
  - Development:
    - Setup: development/setup.md
    - Workflow: development/workflow.md
    - Testing: development/testing.md
  - Deployment: deployment.md

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourorg/miraiworks
