# Ruff configuration for MiraiWorks backend
target-version = "py311"
line-length = 88
indent-width = 4

# Exclude directories from linting and formatting
exclude = [
    "alembic/",
    "alembic/versions/",
    ".git",
    ".venv",
    "__pycache__",
]

[lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
# Plus additional rules for better code quality
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
    "SIM", # flake8-simplify
]

# Never enforce these rules
ignore = [
    "E501",  # Line too long (handled by formatter)
    "B008",  # Do not perform function calls in argument defaults
    "C901",  # Too complex
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
# Tests can use magic values, assertions, etc.
"tests/**/*.py" = [
    "S101",   # Use of assert
    "PLR2004", # Magic value
]

# Allow print statements in scripts
"scripts/**/*.py" = ["T201"]
"*.py" = ["T201"]  # Allow print in all files for now

[format]
# Use single quotes for strings.
quote-style = "double"

# Indent with spaces, rather than tabs.
indent-style = "space"

# Respect magic trailing commas.
skip-magic-trailing-comma = false

# Automatically detect the appropriate line ending.
line-ending = "auto"