version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: miraiworks-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrms
      MYSQL_USER: hrms
      MYSQL_PASSWORD: hrms123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - miraiworks

  # Redis for caching and pub/sub
  redis:
    image: redis:7-alpine
    container_name: miraiworks-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - miraiworks

  # MinIO S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: miraiworks-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - miraiworks

  # ClamAV Antivirus
  clamav:
    image: clamav/clamav:stable
    container_name: miraiworks-clamav
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
    networks:
      - miraiworks

  # Mailpit for email testing
  mailpit:
    image: axllent/mailpit:latest
    container_name: miraiworks-mailpit
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - miraiworks

volumes:
  mysql_data:
  redis_data:
  minio_data:
  clamav_data:

networks:
  miraiworks:
    driver: bridge