"""Add cover_photo_url to user_settings

Revision ID: 20251012001
Revises: 36d34aa655e8
Create Date: 2025-10-12 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20251012001"
down_revision: str | None = "36d34aa655e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings",
        sa.Column("cover_photo_url", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "cover_photo_url")
    # ### end Alembic commands ###
