"""Add video_call_type to interviews table (simple)

Revision ID: 903e6731d7d2
Revises: 1afe6001ccfc
Create Date: 2025-09-22 13:20:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "903e6731d7d2"
down_revision: str | None = "1afe6001ccfc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interviews", sa.Column("video_call_type", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interviews", "video_call_type")
    # ### end Alembic commands ###
