"""Remove theme column from user_settings

Revision ID: 95de50a27612
Revises: 45f3b411a417
Create Date: 2025-09-12 12:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95de50a27612"
down_revision: str | None = "45f3b411a417"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "theme")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings",
        sa.Column(
            "theme", sa.String(length=20), nullable=False, server_default="system"
        ),
    )
    # ### end Alembic commands ###
