export interface PrefectureOption {
  code: string;
  nameJa: string;
  nameEn: string;
}

export const PREFECTURES: PrefectureOption[] = [
  { code: 'hokkaido', nameJa: '北海道', nameEn: 'Hokkaido' },
  { code: 'aomori', nameJa: '青森県', nameEn: 'Aomori' },
  { code: 'iwate', nameJa: '岩手県', nameEn: 'Iwate' },
  { code: 'miyagi', nameJa: '宮城県', nameEn: 'Miyagi' },
  { code: 'akita', nameJa: '秋田県', nameEn: 'Akita' },
  { code: 'yamagata', nameJa: '山形県', nameEn: 'Yamagata' },
  { code: 'fukushima', nameJa: '福島県', nameEn: 'Fukushima' },
  { code: 'ibaraki', nameJa: '茨城県', nameEn: 'Ibaraki' },
  { code: 'tochigi', nameJa: '栃木県', nameEn: 'Tochigi' },
  { code: 'gunma', nameJa: '群馬県', nameEn: 'Gunma' },
  { code: 'saitama', nameJa: '埼玉県', nameEn: 'Saitama' },
  { code: 'chiba', nameJa: '千葉県', nameEn: 'Chiba' },
  { code: 'tokyo', nameJa: '東京都', nameEn: 'Tokyo' },
  { code: 'kanagawa', nameJa: '神奈川県', nameEn: 'Kanagawa' },
  { code: 'niigata', nameJa: '新潟県', nameEn: 'Niigata' },
  { code: 'toyama', nameJa: '富山県', nameEn: 'Toyama' },
  { code: 'ishikawa', nameJa: '石川県', nameEn: 'Ishikawa' },
  { code: 'fukui', nameJa: '福井県', nameEn: 'Fukui' },
  { code: 'yamanashi', nameJa: '山梨県', nameEn: 'Yamanashi' },
  { code: 'nagano', nameJa: '長野県', nameEn: 'Nagano' },
  { code: 'gifu', nameJa: '岐阜県', nameEn: 'Gifu' },
  { code: 'shizuoka', nameJa: '静岡県', nameEn: 'Shizuoka' },
  { code: 'aichi', nameJa: '愛知県', nameEn: 'Aichi' },
  { code: 'mie', nameJa: '三重県', nameEn: 'Mie' },
  { code: 'shiga', nameJa: '滋賀県', nameEn: 'Shiga' },
  { code: 'kyoto', nameJa: '京都府', nameEn: 'Kyoto' },
  { code: 'osaka', nameJa: '大阪府', nameEn: 'Osaka' },
  { code: 'hyogo', nameJa: '兵庫県', nameEn: 'Hyogo' },
  { code: 'nara', nameJa: '奈良県', nameEn: 'Nara' },
  { code: 'wakayama', nameJa: '和歌山県', nameEn: 'Wakayama' },
  { code: 'tottori', nameJa: '鳥取県', nameEn: 'Tottori' },
  { code: 'shimane', nameJa: '島根県', nameEn: 'Shimane' },
  { code: 'okayama', nameJa: '岡山県', nameEn: 'Okayama' },
  { code: 'hiroshima', nameJa: '広島県', nameEn: 'Hiroshima' },
  { code: 'yamaguchi', nameJa: '山口県', nameEn: 'Yamaguchi' },
  { code: 'tokushima', nameJa: '徳島県', nameEn: 'Tokushima' },
  { code: 'kagawa', nameJa: '香川県', nameEn: 'Kagawa' },
  { code: 'ehime', nameJa: '愛媛県', nameEn: 'Ehime' },
  { code: 'kochi', nameJa: '高知県', nameEn: 'Kochi' },
  { code: 'fukuoka', nameJa: '福岡県', nameEn: 'Fukuoka' },
  { code: 'saga', nameJa: '佐賀県', nameEn: 'Saga' },
  { code: 'nagasaki', nameJa: '長崎県', nameEn: 'Nagasaki' },
  { code: 'kumamoto', nameJa: '熊本県', nameEn: 'Kumamoto' },
  { code: 'oita', nameJa: '大分県', nameEn: 'Oita' },
  { code: 'miyazaki', nameJa: '宮崎県', nameEn: 'Miyazaki' },
  { code: 'kagoshima', nameJa: '鹿児島県', nameEn: 'Kagoshima' },
  { code: 'okinawa', nameJa: '沖縄県', nameEn: 'Okinawa' }
];
