name: Frontend - Quality & Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  frontend:
    name: Frontend Quality & Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Dependencies
      working-directory: ./frontend
      env:
        CI: true
        HUSKY: 0
      run: |
        npm ci
        echo "Dependencies installed successfully"

    - name: TypeScript Type Checking
      id: typecheck
      continue-on-error: true
      working-directory: ./frontend
      run: |
        echo "## 📘 TypeScript Type Checking" | tee typecheck-report.txt
        npm run typecheck 2>&1 | tee -a typecheck-report.txt
        TYPECHECK_EXIT=${PIPESTATUS[0]}

        if [ $TYPECHECK_EXIT -eq 0 ]; then
          echo "✅ No type errors found"
        else
          echo "❌ Type errors found - see details above"
        fi

        exit $TYPECHECK_EXIT

    - name: ESLint
      id: lint
      continue-on-error: true
      working-directory: ./frontend
      run: |
        echo "## 🔍 ESLint Results" | tee lint-report.txt
        npm run lint 2>&1 | tee -a lint-report.txt
        LINT_EXIT=${PIPESTATUS[0]}

        if [ $LINT_EXIT -eq 0 ]; then
          echo "✅ No linting errors found"
        else
          echo "❌ Linting errors found - see details above"
        fi

        exit $LINT_EXIT

    - name: Build Application
      id: build
      continue-on-error: true
      working-directory: ./frontend
      env:
        NODE_ENV: production
      run: |
        echo "## 🏗️ Building Next.js Application" | tee build-report.txt
        npm run build:ci 2>&1 | tee -a build-report.txt
        BUILD_EXIT=${PIPESTATUS[0]}

        if [ $BUILD_EXIT -eq 0 ]; then
          echo "✅ Build completed successfully"
        else
          echo "❌ Build failed - see details above"
        fi

        exit $BUILD_EXIT

    - name: Generate Report
      if: always()
      working-directory: ./frontend
      run: |
        echo "## 🎨 Frontend Quality Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Check | Result |" >> $GITHUB_STEP_SUMMARY
        echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| TypeScript | ${{ steps.typecheck.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| ESLint | ${{ steps.lint.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Build | ${{ steps.build.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ "${{ steps.typecheck.outcome }}" != "success" ]; then
          echo "### ❌ TypeScript Errors (First 20)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          head -20 typecheck-report.txt >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "No report available" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi

        if [ "${{ steps.lint.outcome }}" != "success" ]; then
          echo "### ❌ ESLint Errors (First 20)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          head -20 lint-report.txt >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "No report available" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi

        if [ "${{ steps.build.outcome }}" != "success" ]; then
          echo "### ❌ Build Errors (Last 30 lines)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          tail -30 build-report.txt >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "No report available" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload Error Reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: frontend-error-reports
        path: |
          frontend/typecheck-report.txt
          frontend/lint-report.txt
          frontend/build-report.txt
        retention-days: 30

    - name: Quality Gate
      if: always()
      working-directory: ./frontend
      run: |
        echo "=== Quality Gate Check ==="
        FAILED=0

        if [ "${{ steps.typecheck.outcome }}" != "success" ]; then
          echo "❌ TypeScript type checking failed"
          echo ""
          echo "Type errors (first 30 lines):"
          if [ -f typecheck-report.txt ]; then
            echo "📄 Found typecheck-report.txt ($(wc -l < typecheck-report.txt) lines)"
            head -30 typecheck-report.txt
          else
            echo "⚠️  typecheck-report.txt not found!"
          fi
          echo ""
          FAILED=1
        fi

        if [ "${{ steps.lint.outcome }}" != "success" ]; then
          echo "❌ ESLint failed"
          echo ""
          echo "Linting errors (first 30 lines):"
          if [ -f lint-report.txt ]; then
            echo "📄 Found lint-report.txt ($(wc -l < lint-report.txt) lines)"
            head -30 lint-report.txt
          else
            echo "⚠️  lint-report.txt not found!"
          fi
          echo ""
          FAILED=1
        fi

        if [ "${{ steps.build.outcome }}" != "success" ]; then
          echo "❌ Build failed"
          echo ""
          echo "Build errors (last 30 lines):"
          if [ -f build-report.txt ]; then
            echo "📄 Found build-report.txt ($(wc -l < build-report.txt) lines)"
            tail -30 build-report.txt
          else
            echo "⚠️  build-report.txt not found!"
          fi
          echo ""
          FAILED=1
        fi

        if [ $FAILED -eq 1 ]; then
          echo "❌ Frontend quality checks failed"
          echo ""
          echo "To fix:"
          echo "  - Types: cd frontend && npm run typecheck"
          echo "  - Linting: cd frontend && npm run lint:fix"
          echo "  - Build: cd frontend && npm run build"
          echo ""
          echo "📥 Full error reports available in workflow artifacts"
          exit 1
        else
          echo "✅ All frontend checks passed"
        fi
