name: Frontend - Quality & Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  frontend:
    name: Frontend Quality & Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Dependencies
      working-directory: ./frontend
      env:
        CI: true
        HUSKY: 0
      run: |
        npm ci
        echo "Dependencies installed successfully"

    - name: TypeScript Type Checking
      id: typecheck
      working-directory: ./frontend
      run: |
        echo "Running TypeScript type checking..."
        npm run typecheck
        echo "Type checking completed"

    - name: ESLint
      id: lint
      working-directory: ./frontend
      run: |
        echo "Running ESLint..."
        npm run lint
        echo "Linting completed"

    - name: Build Application
      id: build
      working-directory: ./frontend
      env:
        NODE_ENV: production
      run: |
        echo "Building Next.js application..."
        npm run build:ci
        echo "Build completed successfully"

    - name: Generate Report
      if: always()
      run: |
        echo "## 🎨 Frontend Quality Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Check | Result |" >> $GITHUB_STEP_SUMMARY
        echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| TypeScript | ${{ steps.typecheck.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| ESLint | ${{ steps.lint.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Build | ${{ steps.build.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY

    - name: Quality Gate
      if: failure()
      run: |
        echo "❌ Frontend quality checks failed"
        echo "To fix types: cd frontend && npm run typecheck"
        echo "To fix linting: cd frontend && npm run lint:fix"
        exit 1
